# Generated by Django 5.1.3 on 2025-04-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_type',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='next_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='parts_replaced',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
    ]
