# Generated by Django 5.1.3 on 2025-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_maintenance_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Operations', 'Operations')], default='Employee', max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Cleared', 'Cleared'), ('Flagged', 'Flagged')], default='Active', max_length=20),
        ),
    ]
